version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
    - 3.7.0
  - dependency-name: postcss-loader
    versions:
    - 3.0.0
    - 5.0.0
    - 5.1.0
  - dependency-name: "@angular/platform-browser-dynamic"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.2
    - 11.2.3
    - 11.2.4
  - dependency-name: typescript
    versions:
    - 2.9.2
    - 4.1.5
    - 4.2.2
  - dependency-name: "@angular/animations"
    versions:
    - 11.1.0
    - 11.1.2
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
  - dependency-name: file-loader
    versions:
    - 2.0.0
