import { SelectComponent } from './components/select/select.component';
import { HeadlineComponent } from './components/headline/headline.component';
import { AppComponent } from './app.component';

import {
  DialogComponent,
  DialogCreateCaseComponent,
  BackComponent,
  SubcategoryComponent,
  ConfirmComponent,
  SearchComponent,
  LoadingComponent,
  DialogVendorComponent,
  FilterComponent,
  LeftMenuComponent
} from './components';


import {
  CaseComponent,
  CaseDetailComponent,
  HomeComponent,
  LoginComponent,
  QueryComponent,
  CaseSearchComponent,
  UserManagementComponent,
  TargetsComponent,
  TargetComponent,
  TargetsSearchComponent,
  HomeTargetsComponent,
  HomeUsersComponent,
  HomeUserStatisticComponent,
  HomeSuccessProfilesComponent,
  HomeSentimentMonitorComponent,
  HomeMonthlyStatisticsComponent,
  HomeTimelineComponent,
  AvatarsComponent,
  AuditTrailComponent,
  TargetDetailComponent,
  TargetDetailBlockcheinComponent,
  ProfileFullDetailsComponent,
  ProfileFullDetailsBlockcheinComponent
} from './pages';

import {
  DrugsComponent,
  DrugsDetailsComponent,
  WeaponsComponent,
  WeaponDetailsComponent,
  CounterfeitsComponent,
  CounterfeitsDetailsComponent,
  DocsComponent,
  DocsDetailsComponent,
  EbooksComponent,
  EbooksDetailsComponent,
  DigitalGoodsComponent,
  DigitalGoodsDetailsComponent,
  PrescriptionComponent,
  PrescriptionDetailsComponent,
  FraudComponent,
  FraudDetailsComponent,
  HackingComponent,
  HackingDetailsComponent,
  IdsPassportsComponent,
  IdsPassportsDetailsComponent,
  MoneyComponent,
  MoneyDetailsComponent,
  ReligionComponent,
  ReligionDetailsComponent,
  SoftwareComponent,
  SoftwareDetailsComponent,
  BankingComponent,
  SecurityAndHostingDetailsComponent,
  SecurityAndHostingComponent,
  TicketsAndBookingsDetailsComponent,
  TicketsAndBookingsComponent,
  ServicesComponent,
  ServicesDetailsComponent,
  SteroidsComponent,
  SteroidsDetailsComponent,
  LuxuryComponent,
  LuxuryDetailsComponent,
  HardwareComponent,
  HardwareDetailsComponent,
  GuidesAndTutorialsComponent,
  GuidesAndTutorialsDetailsComponent,
  FashionComponent,
  FashionDetailsComponent,
  CardingWareComponent,
  CardingWareDetailsComponent,
  OtherDetailsComponent,
  OtherComponent,
  BlockchainComponent,
} from './pages/categories';

import { WeaponFilterPipe, WeaponLimitPipe, VendorRatingPipe, SortingUsersPipe } from './pipes';

import { GoogleChart } from './directives';
import {
  ContentComponent,
  QueryLayoutComponent,
  FooterComponent
} from './layouts';
import {
  ListingsFromUsernameComponent,
  RatingsComponent,
  RgpKeyComponent,
  TermsAndConditionsComponent,
  VendorInformationsComponent
} from './pages/target-detail/profile-full-details';
import {TransactionsComponent} from './pages/target-detail-blockchein/profile-full-details-blockchein';
import { QueryDialogComponent } from './components/dialog/query-dialog/query-dialog.component';

export const AppDeclarations = [
  AppComponent,
  CaseComponent,
  CaseSearchComponent,
  CaseDetailComponent,
  TargetComponent,
  HomeTargetsComponent,
  HomeUsersComponent,
  AvatarsComponent,
  HomeUserStatisticComponent,
  HomeSuccessProfilesComponent,
  HomeSentimentMonitorComponent,
  HomeMonthlyStatisticsComponent,
  AuditTrailComponent,
  HeadlineComponent,
  HomeTimelineComponent,
  LeftMenuComponent,
  SelectComponent,
  TargetsSearchComponent,
  HomeComponent,
  QueryComponent,
  TargetsComponent,
  TargetDetailComponent,
  UserManagementComponent,
  WeaponFilterPipe,
  ProfileFullDetailsComponent,
  ProfileFullDetailsBlockcheinComponent,
  ListingsFromUsernameComponent,
  RatingsComponent,
  RgpKeyComponent,
  TermsAndConditionsComponent,
  VendorInformationsComponent,
  VendorRatingPipe,
  WeaponLimitPipe,
  SortingUsersPipe,
  GoogleChart,
  ContentComponent,
  FooterComponent,
  QueryLayoutComponent,
  DrugsComponent,
  DrugsDetailsComponent,
  WeaponsComponent,
  WeaponDetailsComponent,
  CounterfeitsComponent,
  CounterfeitsDetailsComponent,
  DocsComponent,
  DocsDetailsComponent,
  EbooksComponent,
  EbooksDetailsComponent,
  DigitalGoodsComponent,
  DigitalGoodsDetailsComponent,
  PrescriptionComponent,
  PrescriptionDetailsComponent,
  SecurityAndHostingDetailsComponent,
  SecurityAndHostingComponent,
  TicketsAndBookingsDetailsComponent,
  TicketsAndBookingsComponent,
  ServicesComponent,
  ServicesDetailsComponent,
  SteroidsComponent,
  SteroidsDetailsComponent,
  LuxuryComponent,
  LuxuryDetailsComponent,
  HardwareComponent,
  HardwareDetailsComponent,
  GuidesAndTutorialsComponent,
  GuidesAndTutorialsDetailsComponent,
  FashionComponent,
  FashionDetailsComponent,
  CardingWareComponent,
  CardingWareDetailsComponent,
  OtherDetailsComponent,
  OtherComponent,
  FraudComponent,
  FraudDetailsComponent,
  HackingComponent,
  HackingDetailsComponent,
  IdsPassportsComponent,
  IdsPassportsDetailsComponent,
  MoneyComponent,
  MoneyDetailsComponent,
  ReligionComponent,
  ReligionDetailsComponent,
  SoftwareComponent,
  SoftwareDetailsComponent,
  TransactionsComponent,
  TargetDetailBlockcheinComponent,
  BankingComponent,
  BlockchainComponent,
  /*----- Components -----*/
  DialogComponent,
  DialogCreateCaseComponent,
  BackComponent,
  SubcategoryComponent,
  ConfirmComponent,
  SearchComponent,
  LoadingComponent,
  DialogVendorComponent,
  FilterComponent,
  QueryDialogComponent,

];
